'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { api } from '@/lib/api';
import { useAuthStore } from '@/store/authStore';
import { Bot, Calendar, Clock, MessageSquare, RefreshCw, FileText, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';

interface DbMessage {
  id: number;
  role: 'user' | 'assistant' | 'tool';
  content?: string;
  toolCalls?: any;
  createdAt: string;
}

export default function AiHistoryPage() {
  const router = useRouter();
  const params = useParams();
  const locale = (params?.locale as string) || 'en';
  const { user, hydrated } = useAuthStore();

  const [history, setHistory] = useState<DbMessage[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchHistory = async () => {
    try {
      setLoading(true);
      const res = await api.get('/ai/history');
      setHistory(res.data);
    } catch (err) {
      console.error('Failed to load past chat logs', err);
      toast.error('Unable to fetch past JARVIS conversations');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (hydrated && !user) {
      router.push(`/${locale}/auth/login`);
      return;
    }
    if (user) {
      fetchHistory();
    }
  }, [user, hydrated]);

  const handleExportSinglePDF = (msg: DbMessage) => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      pdf.setFont('helvetica', 'normal');
      
      // Title header
      pdf.setFontSize(16);
      pdf.text('Beauty Parlé JARVIS AI log', 20, 20);
      
      pdf.setFontSize(10);
      pdf.text(`User: ${user?.name || 'Customer'}`, 20, 30);
      pdf.text(`Date: ${new Date(msg.createdAt).toLocaleString()}`, 20, 35);
      pdf.line(20, 40, 190, 40);

      pdf.setFontSize(11);
      pdf.text(`Message details:`, 20, 50);

      const splitText = pdf.splitTextToSize(msg.content || 'Action executed', 160);
      pdf.text(splitText, 20, 60);

      pdf.save(`jarvis-log-${msg.id}.pdf`);
      toast.success('Successfully downloaded PDF log!');
    } catch {
      toast.error('Failed to export PDF');
    }
  };

  if (!hydrated || loading) {
    return (
      <>
        <Header />
        <main className="min-h-screen py-12 bg-secondary/10 flex items-center justify-center">
          <div className="flex flex-col items-center gap-2">
            <RefreshCw className="w-8 h-8 animate-spin text-primary" />
            <span className="text-xs text-muted-foreground font-semibold">Loading your AI log history...</span>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Header />
      <main className="min-h-screen py-12 bg-secondary/15">
        <div className="container mx-auto px-4 max-w-4xl space-y-8">
          
          {/* Headline */}
          <div className="space-y-2">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-primary/10 text-primary text-xs font-bold rounded-full">
              <Bot className="w-3.5 h-3.5" /> AI memory logs
            </div>
            <h1 className="text-3xl font-playfair font-bold">JARVIS Assistant Memory</h1>
            <p className="text-xs text-muted-foreground">
              Review your past requests, tool calls, and charts generated by the JARVIS assistant.
            </p>
          </div>

          {history.length === 0 ? (
            <div className="bg-card p-16 rounded-3xl border border-border/50 text-center space-y-4 shadow-sm">
              <MessageSquare className="w-12 h-12 mx-auto text-muted-foreground/30 stroke-[1.2]" />
              <div>
                <h3 className="font-bold text-foreground text-base">No AI logs found</h3>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Launch the floating assistant drawer at the bottom right to start a conversation!
                </p>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              {history.map((msg) => (
                <div 
                  key={msg.id}
                  className="bg-card p-5 rounded-2xl border border-border/40 shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-4 hover:border-primary/30 transition-all duration-200"
                >
                  <div className="space-y-2 flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className={`px-2 py-0.5 rounded-md text-[9px] font-bold uppercase tracking-wider ${
                        msg.role === 'user' ? 'bg-primary/10 text-primary' :
                        msg.role === 'tool' ? 'bg-amber-100 text-amber-700' :
                        'bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300'
                      }`}>
                        {msg.role}
                      </span>
                      <div className="flex items-center gap-1 text-[10px] text-muted-foreground font-semibold">
                        <Calendar className="w-3 h-3" />
                        <span>{new Date(msg.createdAt).toLocaleDateString()}</span>
                        <Clock className="w-3 h-3 ml-1.5" />
                        <span>{new Date(msg.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                      </div>
                    </div>

                    <p className="text-xs text-foreground font-medium leading-relaxed break-words line-clamp-3">
                      {msg.content || (msg.toolCalls ? `Invoked tool function: ${msg.toolCalls.name}` : 'Acknowledge')}
                    </p>
                  </div>

                  {msg.content && (
                    <button
                      onClick={() => handleExportSinglePDF(msg)}
                      className="px-4 py-2 border border-border text-muted-foreground hover:text-foreground hover:bg-secondary rounded-xl text-xs font-bold transition flex items-center gap-1.5 shrink-0 cursor-pointer w-full md:w-auto justify-center"
                    >
                      <FileText className="w-4 h-4" />
                      <span>Download log</span>
                    </button>
                  )}
                </div>
              ))}
            </div>
          )}

        </div>
      </main>
      <Footer />
    </>
  );
}
